apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: discovery-engine-accuknox-knoxautopolicy-latest-maint-tools-access
  namespace: accuknox-agents
spec:
  action: Audit
  message: restricted maintenance tool access attempt detected
  process:
    matchDirectories:
    - dir: /sbin/
      recursive: true
  selector:
    matchLabels:
      app: discovery-engine
  severity: 1
  tags:
  - PCI_DSS
  - MITRE
