apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: kubearmor-host-policy-manager-gcr-io-kubebuilder-kube-rbac-proxy-v0-8-0-restrict-automount-sa-token
  namespace: kube-system
spec:
  selector:
    matchLabels:
      kubearmor-app: kubearmor-host-policy-manager
