apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: local-path-provisioner-kindest-local-path-provisioner-v0-0-22-kind-0-write-under-dev-dir
  namespace: local-path-storage
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /dev/
      readOnly: true
      recursive: true
  message: Alert! File creation under /dev/ directory detected.
  selector:
    matchLabels:
      app: local-path-provisioner
  severity: 5
  tags:
  - NIST
  - NIST_800-53_AU-2
  - NIST_800-53_SI-4
  - MITRE
  - MITRE_T1036_masquerading
