apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: local-path-provisioner-kindest-local-path-provisioner-v0-0-22-kind-0-system-network-env-mod
  namespace: local-path-storage
spec:
  action: Block
  file:
    matchPaths:
    - path: /etc/issue
      readOnly: true
    - path: /etc/issue.net
      readOnly: true
    - path: /etc/hosts
      readOnly: true
    - path: /etc/sysconfig/network
      readOnly: true
  message: Alert! Modification to system network files detected
  selector:
    matchLabels:
      app: local-path-provisioner
  severity: 5
  tags:
  - CIS
  - CIS_Linux
  - CIS_4_Logging_and_Aduditing
  - CIS_4.1.1_Data_Retention
  - CIS_4.1.7_system_network_environment
