apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: local-path-provisioner-kindest-local-path-provisioner-v0-0-22-kind-0-trusted-cert-mod
  namespace: local-path-storage
spec:
  action: Block
  file:
    matchDirectories:
    - dir: /etc/ssl/
      readOnly: true
      recursive: true
    - dir: /etc/pki/
      readOnly: true
      recursive: true
    - dir: /usr/local/share/ca-certificates/
      readOnly: true
      recursive: true
  message: Credentials modification denied
  selector:
    matchLabels:
      app: local-path-provisioner
  severity: 1
  tags:
  - MITRE
  - MITRE_T1552_unsecured_credentials
