apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: nginx-2-nginx-latest-restrict-automount-sa-token
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-2
