apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: nginx-2-nginx-latest-maint-tools-access
  namespace: default
spec:
  action: Audit
  message: restricted maintenance tool access attempt detected
  process:
    matchDirectories:
    - dir: /sbin/
      recursive: true
  selector:
    matchLabels:
      app: nginx-2
  severity: 1
  tags:
  - PCI_DSS
  - MITRE
