apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: kubearmor-annotation-manager-kubearmor-kubearmor-annotation-manager-latest-maint-tools-access
  namespace: kube-system
spec:
  action: Audit
  message: restricted maintenance tool access attempt detected
  process:
    matchDirectories:
    - dir: /sbin/
      recursive: true
  selector:
    matchLabels:
      kubearmor-app: kubearmor-annotation-manager
  severity: 1
  tags:
  - PCI_DSS
  - MITRE
